@include('partials.routes.sections.classification')
@include('partials.routes.sections.crew')
@include('partials.routes.sections.relations')
@include('partials.routes.sections.armaments')
@include('partials.routes.sections.systems')
