@include('partials.routes.sections.key-information')
@include('partials.routes.sections.service')
@include('partials.routes.sections.crew')
@include('partials.routes.sections.relations')
@include('partials.routes.sections.armaments')
@include('partials.routes.sections.systems')
